# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'todoey' do
  use_frameworks!

  # Pods for todoey
  pod 'RealmSwift'

  pod 'SwipeCellKit', '2.5.4'

  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'

end
