# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'tobedone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tobedone
  pod 'Firebase/Core'
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'SVProgressHUD'
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
  pod 'RealmSwift'
  pod 'SwipeCellKit', '2.5.4'

end
